name: lint, test, deploy




on:
  push:

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      with: actions/checkout@v4
    - name: linting
      run: npm lint
    - name: testing
      run: npm test
    - name: buidling
      run: npm buil
