name: lint, test, deploy
on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: npm install
      - name: linting
        run: npm run lint
      - name: testing
        run: npm run test
      - name: buidling
        run: npm build
